/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    // Admin templates (embedded in the Go binary).
    "./internal/render/templates/admin/*.html",
    // Public templates extracted from DB (generated by build-public-css.sh).
    "./.tailwind-content/**/*.html",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
