// Copyright (c) 2026 Madalin Gabriel Ignisca <hi@madalin.me>
// Copyright (c) 2026 Vlah Software House SRL <contact@vlah.sh>
// All rights reserved. See LICENSE for details.

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    // Admin templates (embedded in the Go binary).
    "./internal/render/templates/admin/*.html",
    // Public templates extracted from DB (generated by build-public-css.sh).
    "./.tailwind-content/**/*.html",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
